exec ~/.fehbg &
[ -f ~/.config/X11/xresources ] && xrdb -load ~/.config/X11/xresources
#Start conpositor
picom -b --config .config/picom/picom.conf
#Start he bar
dwmblocks &
dunst &
#transmission-daemon &
#exec bspwm
# Start dwm
while true; do
    exec dwm
done
