[env]
TERM = "xterm-256color"

[font]
size = 13.0

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mode = "~Alt"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mode = "~Alt"
mods = "Alt"

[window]
opacity = 0.95
