#!/bin/sh
connect(){
    bluetoothctl -- power on >/dev/null && bluetoothctl -- devices | dmenu | cut -d" " -f2 | xargs bluetoothctl -- connect
}
disconnect(){
    bluetoothctl -- devices | dmenu | cut -d" " -f2 | xargs bluetoothctl -- disconnect
}
powon(){
    bluetoothctl -- power on >/dev/null && echo "Powered on!"
}
powoff(){
    bluetoothctl -- power off >/dev/null && echo "Powered off!"
}
pair(){
    dev=$(bluetoothctl -- devices | dmenu | cut -d" " -f2)
    bluetoothctl -- pair "$dev"
    bluetoothctl -- trust "$dev"
    bluetoothctl -- connect "$dev"
}

scanon(){
    echo "Not implemented"
}

menu=$(cat << EOF
Connect
Disconnect
Power On
Power Off
Scan On
Pair New
EOF
)

case "$(echo "$menu" | dmenu -i -p "Bluetooth")" in
    "Connect") connect ;;
    "Disconnect") disconnect ;;
    "Power On") powon ;;
    "Power Off") powoff ;;
    "Scan On") scanon &;;
    "Pair New") pair ;;
esac | xargs -I{} notify-send "{}"
