#!/bin/bash
intern=LVDS-1
extern=DP-2

if xrandr | grep "$extern disconnected"; then
    xrandr --output "$extern" --off --output "$intern" --auto && exec ~/.fehbg
else
    xrandr --output "$intern" --off --output "$extern" --auto && exec ~/.fehbg
fi
