#!/bin/sh
url=$(sfeed_plain "$HOME/.local/share/sfeed/"* | grep ^N | dmenu -l 35 -i | sed -n 's@^.* \([a-zA-Z]*://\)\(.*\)$@\1\2@p')

test -n "${url}" && case "${url}" in
	*mkv|*webm|*mp4|*mp3|*twitch*|*youtube.com/watch*|*youtube.com/playlist*|*youtu.be*|*hooktube.com*|*bitchute.com*|*videos.lukesmith.xyz*|*odysee.com*)
		setsid -f mpv -quiet "${url}" >/dev/null 2>&1 ;;
	*png|*jpg|*jpe|*jpeg|*gif)
		curl -sL "$1" > "/tmp/$(echo "${url}" | sed "s/.*\///")" && sxiv -a "/tmp/$(echo "$1" | sed "s/.*\///")"  >/dev/null 2>&1 & ;;
    *)
        setsid -f $BROWSER "${url}" 2>&1;;
esac
