#!/bin/sh

# Set variables so pass cmd will work
eval "$(grep -h -- \
	"^\s*\(export \)\?\(MBSYNCRC\|PASSWORD_STORE_DIR\|NOTMUCH_CONFIG\|GNUPGHOME\)=" \
	"$HOME/.profile" "$HOME/.bash_profile" "$HOME/.zprofile"  "$HOME/.config/zsh/.zprofile" "$HOME/.zshenv" \
	"$HOME/.bashrc" "$HOME/.zshrc" "$HOME/.config/zsh/.zshrc" "$HOME/.pam_environment" 2>/dev/null)"

export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
#export GPG_TTY=$TTY
alias mbsync="mbsync -c $MBSYNCRC"
mbsync -a
