#!/bin/sh

if [ $# -eq 1 ]; then
    selected=$1
else
    selected=$(fd . ~/S Syncthing/AU ~/Dokumenter/| fzf)
fi

dirname=`basename $selected`

tmux a -client -t $dirname
if [ $? -eq 0 ]; then
    exit 0
fi

tmux new-session -c $selected -d -s $dirname && tmux a -t $dirname || tmux new -c $selected -A -s $dirname
