#!/bin/sh
#
PDIR=~/Dokumenter/music/playlists
url=$(xclip -o)
name=$(yt-dlp --no-playlist "$url" -O "%(title)s")
plist="$(ls $PDIR | dmenu -i -p "Playlist" )"
sta="$(printf "\n" | dmenu -i -p "Start time" )"
end="$(printf "\n" | dmenu -i -p "End time" )"
sta=${sta:-0}
end=${end:-inf}

if [[ $sta -eq 0 && $end -eq "inf" ]]; then
    tcode=""
else
    tcode=$(echo "--download-sections \"*$sta-$end\"")
fi

notify-send "Adding $name"
echo "$url" $tcode >> ~/Dokumenter/music/misc/music.txt
#~/Dokumenter/music/misc/ytpl && notify-send "✅ $name" \
#    && [ $plist ] && echo "$name" > $PDIR/$plist \
