vim.opt.spelllang="en_us,da"
vim.opt.wildmenu=true
vim.opt.number=true
vim.opt.relativenumber=true
vim.opt.smartcase=true
vim.opt.ignorecase=true
vim.opt.incsearch=true
vim.opt.smartindent=true
vim.opt.shiftwidth=4
vim.opt.expandtab=true
vim.opt.tabstop=4
vim.opt.softtabstop=4
vim.opt.wrap=false
vim.opt.signcolumn="yes"
vim.opt.termguicolors=true
vim.opt.completeopt={"menuone","menu"}
vim.opt.makeprg="make #1:r.pdf"
