hack: &hack Roboto Mono:pixelsize=16
bg_default: &bg_default {stack: [{background: {color: 81A1C1ff}}, {underline: {size: 4, color: D8DEE9ff}}]}
bar:
  height: 30
  location: top
  font: JuliaMono:pixelsize=10
  spacing: 2
  margin: 0
  layer: bottom
  foreground: eeeeeeff
  background: 2E3440dd

  left:
    - river:
        anchors:
          base: &river_base
            left-margin: 10
            right-margin: 13 
            conditions:
              id == 1: {string: {text: 1, font: *hack}}  
              id == 2: {string: {text: 2, font: *hack}}  
              id == 3: {string: {text: 3, font: *hack}}  
              id == 4: {string: {text: 4, font: *hack}}  
              id == 5: {string: {text: 5, font: *hack}}  
              id == 6: {string: {text: 6, font: *hack}}  
              id == 7: {string: {text: 7, font: *hack}}  
              id == 8: {string: {text: 8, font: *hack}}  
              id == 9: {string: {text: 9, font: *hack}}  
              id == 0: {string: {text: 0, font: *hack}}  
        content:
          map:
            on-click: 
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: D08770ff}}
              state == focused:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied: {empty: {}}
              state == invisible && occupied:
                map:
                  <<: *river_base
                  deco: {underline: {size: 3, color: ea6962ff}}
  right:
    - clock:
        date-format: "%d/%m/%Y"
        content:
          - string: {text: "{date}", right-margin: 5, font: *hack}
          - string: {text: "{time}", right-margin: 20, font: *hack}
    - clock:
        utc: true
        content:
          - string: {text: "{time} UTC", right-margin: 20, font: *hack}
    - battery:
        name: BAT1
        poll-interval: 30000
        content:
          map:
            default: {string: {text: "🔋{capacity}% {estimate}", right-margin: 20, font: *hack}}
            conditions:
              state == charging: {string: {text: "⚡{capacity}% {estimate}", right-margin: 20, font: *hack}}
    - backlight:
        name: intel_backlight
        content:
          - string: {text: "🔆{percent}%", right-margin: 20, font: *hack}
    - pipewire:
        anchors:
          volume: &volume
            conditions:
              muted: {string: {text: "{linear_volume}%", foreground: ff0000ff}}
              ~muted: {string: {text: "{linear_volume}%"}}
        content:
          list:
            items:
              - map:
                  conditions:
                    type == "sink":
                      map:
                        conditions:
                          icon == "audio-headset-bluetooth":
                            string: {text: "🎧  "}
                        default:
                          - ramp:
                              tag: linear_volume
                              items:
                                - string: {text: "{linear_volume}%🔈", font: *hack}
                                - string: {text: "{linear_volume}%🔉", font: *hack}
                                - string: {text: "{linear_volume}%🔊", font: *hack}
                    type == "source":
                      {empty: {}}
